name: deploy_backend

on:
    push:
        branches: [main]
        paths:
            - 'backend/**' # Deploys when push is made from the backend folder'

env:
  AZURE_FUNCTIONAPP_NAME: getazresumecounter    # Set this to your function's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'      # Set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0'           # Set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Actions'
      uses: actions/checkout@main

    - name: 'Login via Azure CLI'
      uses: azure/login@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

     
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    
    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run unit test'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/tests'
        dotnet test

    - name: 'Run Azure Fuctions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }} 
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api/output' 
       
